### ISSUE TITLE
Control Screen sequence speed

### ISSUE THREAD

**Issue by mikekgr** [G6EJD/ESP-Novelty-Xmas-and-NY-Countdown#2]
Dear Sir,
is there any way to control the screen sequencing? 
If there is, please guide me how can do it.

Thanks and Best Regards,
Mike Kranidis

**Comment by G6EJD** [comment]
Hi,
Do you mean speed of transition or sequence of the individual screens, if the former then difficult, but screen sequence is controlled by this line:
FrameCallback frames[] = {drawFrame1, drawFrame2, drawFrame3, drawFrame4};

Example:
FrameCallback frames[] = {drawFrame4, drawFrame3, drawFrame2, drawFrame1};

Would draw the frames backwards. You can put the frames in any order you like, add a new frame by creating the frame function, maybe a copy and then adding to the list like this:
FrameCallback frames[] = {drawFrame1, drawFrame2, drawFrame3, drawFrame4,drawFrame5};

And increasing the frame count by 1:
int frameCount = 5;

**Comment by mikekgr** [comment]
Dear @G6EJD
thanks a lot for your answer. and the information given 

Indeed I meant the speed of transition between the specified ( 4 ) screens.
I am trying to understood why the transition from one screen to the next is taking long time and the possible way to decrease this time.

Thanks and Best Regards,
Mike Kranidis

**Comment by G6EJD** [comment]
Try varying the frame rate,  there is not a lot of time left with the ESP8266 at 30fps:
ui.setTargetFPS(10);

10 would give you more time, but it would slow down the rate too.

**Comment by mikekgr** [comment]
I will try it when at home.
Again, many thanks!

**Comment by G6EJD** [comment]
I recall some discussion on the SQUIX forum about the timers that aren't normally available with his (SQUIX) Library, you can then vary the lag between transitions and other events. Might be worth a look.
